<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>RisTextureToolkit</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <!-- NUGET -->
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>RisTextureToolkit</PackageId>
    <Version>0.1.3</Version>
    <Authors>Erkapic Luka</Authors>
    <Description>The texture toolkit which can be used to load or create texture atlases.</Description>
    <PackageTags>RisGameFramework</PackageTags>
    <RepositoryUrl>https://github.com/luka712/Ris.SpriteToolkit</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="RisKtx2" Version="0.1.4" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
  </ItemGroup>
  <ItemGroup>
    <None Update="runtimes\win-x64\native\ktx.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\ris_texture_toolkit.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\zstd.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
